### PR TITLE
Added new command "repos" to show your repos

### PR DESCRIPTION
**Pull request by subhranshuchoudhury**
## Types of changes

- [ ] Bug/Hot fix (non-breaking change which fixes an bug)
- [x] New feature (non-breaking change which adds a functionality/feature)
- [ ] Refactoring Old Code ( non-breaking change replacing already existing code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** guidelines in repository.
- [x] My pull request has a descriptive title and is attached to an existing issue.
- [x] I haven't repeated the code and it follows established code style of repository.
- [x] My branch is up-to-date with upstream branch.

### CODE REVIEW

**Comment by subhranshuchoudhury** [comment]
@TechSpiritSS accept the PR. Add label.

**Comment by TechSpiritSS** [comment]
I liked this but I think it's better if the repos are sorted by latest instead of name? If you are good with this, then made the changes accordingly else I'll merge this in name order.

**Comment by subhranshuchoudhury** [comment]
> I liked this but I think it's better if the repos are sorted by latest instead of name? If you are good with this, then made the changes accordingly else I'll merge this in name order.

Accept this.. but surely i will sort the array in latest order and fix some bugs after few days. ❤️

**Comment by TechSpiritSS** [comment]
Alright, Great Work 👍

**Pull request merged**
