### PR TITLE
Added exit functionality & corrected a small spelling mistake

### PR DESCRIPTION
**Pull request by akshaykhoje**
Hello @TechSpiritSS !

The script at present does not have an option to exit the script.
However I have done the needful by adding an EXIT option in the "help" or "ls" menu.

Along with this, I have also fixed a typo. "Stating -> Starting"

Please assign the issue raised before a hacktoberfest tag and merge this request.

Thank you so much!

### CODE REVIEW

**Comment by TechSpiritSS** [comment]
Well, the exit function isn't working properly and `ls` UI for exit isn't matching the rest so I am reopening this issue.

**Comment by akshaykhoje** [comment]
So does that mean my PR will be discarded by Hacktoberfest?

**Comment by TechSpiritSS** [comment]
you have time to fix that bug

**Comment by akshaykhoje** [comment]
1. You expect it to be this way right in the **ls** menu:
exit to exit the window

2. What do you mean by not properly working? It closes the window right away. How do you expect the exit functionality should work?

**Comment by TechSpiritSS** [comment]
1. Yes, it should look similar to others.
2. Well, it was not working in Deployed State.

**Pull request merged**
