### PR TITLE
done changes in galaxy ,vibrant, nature,matrix and metalic theme

### LINKED ISSUE #153: want to modify the  themes as it having some error in matrix.css ,metalic.css, nature.css  file
kindly assign me this issue

### PR DESCRIPTION
**Pull request by Nehaaa3121**
i  have resolved the issue  .kindly approve my PR.
issue number :- #153 

Fixes #153  by @TechSpiritSS

### CODE REVIEW

**Comment by TechSpiritSS** [comment]
preview link?

**Comment by Nehaaa3121** [comment]
https://nehaaa3121.github.io/Terminal-Portfolio/

here is my preview link

**Comment by TechSpiritSS** [comment]
Why have you changed the colors of existing themes?

**Comment by Nehaaa3121** [comment]
> 

for making UI design better. you can see the differences in previous themes aren't that much attractive.

**Comment by TechSpiritSS** [comment]
I don't think color scheme was an issue.

**Comment by TechSpiritSS** [comment]
Instead of changing colors, make the design consistent across the themes as there's difference in sizing properties across the themes.

**Comment by Nehaaa3121** [comment]
> 

you can check the galaxy and vibrant themes, they are of the same design that's why I have brought changes in all the themes.

**Comment by TechSpiritSS** [comment]
yes but that wasn't an issue

**Comment by Nehaaa3121** [comment]
> yes but that wasn't an issue

no problem , I have made these changes only because I thought that UI design plays an important role in any project.

**Comment by TechSpiritSS** [comment]
Yes UI plays an important part in any project, if you feel current themes aren't that appealing you're free to create a team of your own and send a PR.

**Pull request closed without merging**
