### PR TITLE
added type to exit functionality

### LINKED ISSUE #53: [Bug]: Change EXIT from Click to Type
### Contact Details

_No response_

### What happened?

The EXIT works on mouse click. 

### What should have happened?

Change that clicks to exit to Type to exit i.e., user type EXIT to EXIT the window. 

### What browsers are you seeing the problem on?

_No response_

### Version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by AshishRaikwar1290**
Fixes #53  by @TechSpiritSS 

## Types of changes
added type to exit functionality

## Description
added type to exit functionality

### CODE REVIEW

**Comment by TechSpiritSS** [comment]
Good one 👍 but remove click to exit functionality from this and try to follow the use of PR Template in future.

**Comment by TechSpiritSS** [comment]
You are having a merge conflict :/

**Comment by TechSpiritSS** [comment]
Great 👍

**Comment by AshishRaikwar1290** [comment]
Okay I will do that

**Pull request merged**
