### PR TITLE
Update README.md

### LINKED ISSUE #120: [Req]: Updating the readme file.
### Contact Details

anishdubey100@gmail.com

### Explain the proposed feature

I think the contributing guidelines in the readme file might not be sufficient for a new contributor.
We can make some changes in the file which makes the process of contributing easier with a step by step contributing process.

### Explain the possible use cases for the feature

This would be helpful for the first-time/new contributors to start contributing.
Also the project will get contributions from many new contributors.

### Any other details you would like to provide?

I would like to work on this issue and contribute to the project.

### PR DESCRIPTION
**Pull request by AnishDubey27**
## Fixes
Fixes #120  

## Types of changes

- [ ] Bug/Hot fix (non-breaking change which fixes an bug)
- [x] New feature (non-breaking change which adds a functionality/feature)
- [ ] Refactoring Old Code ( non-breaking change replacing already existing code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

⟫ Added some images of the technologies used in the making of the project. 
⟫ Added a section "How to make a PR" to help first time contributors. 
⟫ Added "back to top" tabs at 5 places in the file which make navigation through the file easier for the readers.

Preview link: https://github.com/TechSpiritSS/Terminal-Portfolio/commit/d2999ef08a2906c78f6aba796506e1f54f7a2e08

## Checklist:

- [x] I have read the **CONTRIBUTING** guidelines in repository.
- [x] My pull request has a descriptive title and is attached to an existing issue.
- [x] I haven't repeated the code and it follows established code style of repository.
- [x] My branch is up-to-date with upstream branch.

### CODE REVIEW

**Comment by TechSpiritSS** [comment]
Many places contain reference to Weather_Detector

**Comment by TechSpiritSS** [comment]
Add a option for GitHub Desktop as well, GUI is much easier for beginners to get started with.

**Comment by AnishDubey27** [comment]
Done! @TechSpiritSS

**Comment by TechSpiritSS** [comment]
Great Work 🚀

**Pull request merged**
