### PR TITLE
added help -d

### LINKED ISSUE #129: [Req]: add -d tag to help
### Contact Details

techspiritss@duck.com

### Explain the proposed feature

As we are adding new features the help tag is getting messier. The current help tag should only be shown when `help -d` is asked. In case of only `help` show the list of commands as single line.
`about, contribution, calc` and so on.

### Explain the possible use cases for the feature

Cleaner Interface

### Any other details you would like to provide?

_No response_

### PR DESCRIPTION
**Pull request by khushigarg1**
## Fixes

Fixes #129 ] by @[khushigarg1]

## Types of changes

- [x] Bug/Hot fix (non-breaking change which fixes an bug)
- [x] New feature (non-breaking change which adds a functionality/feature)
- [ ] Refactoring Old Code ( non-breaking change replacing already existing code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Preview Link

- [x] I have read the **CONTRIBUTING** guidelines in repository.
- [x] My pull request has a descriptive title and is attached to an existing issue.
- [x] I haven't repeated the code and it follows established code style of repository.
- [x] My branch is up-to-date with upstream branch.

### CODE REVIEW

**Comment by TechSpiritSS** [comment]
- Missing Preview Link
- Merge Conflicts

**Comment by khushigarg1** [comment]
> ## Fixes
> Fixes #129 ] by @[khushigarg1]
> 
> ## Types of changes
> * [x]  Bug/Hot fix (non-breaking change which fixes an bug)
> * [x]  New feature (non-breaking change which adds a functionality/feature)
> * [ ]  Refactoring Old Code ( non-breaking change replacing already existing code)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to change)
> 
> ## Description
> ## Preview Link
https://khushigarg1.github.io/Terminal-Portfolio/

> ## Checklist:
> * [x]  I have read the **CONTRIBUTING** guidelines in repository.
> * [x]  My pull request has a descriptive title and is attached to an existing issue.
> * [x]  I haven't repeated the code and it follows established code style of repository.
> * [x]  My branch is up-to-date with upstream branch.

**Comment by khushigarg1** [comment]
Resolve conflicts button is disable so i am not able to solve conflicts.
Please can you teal me how can i do that ?

conflict

**Comment by TechSpiritSS** [comment]
Merge Conflict

**Comment by khushigarg1** [comment]
> Merge Conflict

I am not able to merge It is showing "only those with write access to this repo can merge pull requests" please give me access to write in this file.

**Comment by TechSpiritSS** [comment]
You need to first pull the latest commit on your local machine and then add your changes to it.

**Comment by TechSpiritSS** [comment]
use GitHub desktop if you are facing issue with Github CLI, it will show you changes visually

**Comment by khushigarg1** [comment]
> You need to first pull the latest commit on your local machine and then add your changes to it.

Okay Thank you I will try!

**Comment by khushigarg1** [comment]
@TechSpiritSS Done! please check

**Comment by TechSpiritSS** [comment]
image
Those shouldn't be clickable links

image
It's working great but do add an option to tell users that using -d tag will give them more information.

Like after commands -
`Type help -d` for detailed help

or something like that

**Comment by khushigarg1** [comment]
> image Those shouldn't be clickable links
> 
> image It's working great but do add an option to tell users that using -d tag will give them more information.
> 
> Like after commands - `Type help -d` for detailed help
> 
> or something like that

Yaa sure I will!

**Comment by TechSpiritSS** [comment]
Great 🚀

**Comment by khushigarg1** [comment]
> Great 🚀

Thank you

**Pull request merged**
