### PR TITLE
Added theme switcher

### LINKED ISSUE #16: Create buttons to change theme
I'd like to add the ability to change between different color themes, much like what normal terminals have. Maybe start with a few preset ones for now, with the possibility of later adding functionality for the user to create their own?

### PR DESCRIPTION
**Pull request by ethapar**
Adds 5 buttons in the menu section that the user can click to switch between different themes for the terminal. Theme palettes were sourced from several other common terminal applications like SecureCRT and PuTTY. Modifying any of them should that be desired is very easily done through each one's individual .css file. 

Any time the page is loaded it defaults to the main theme.  Currently the buttons are set to disappear when viewed on mobile as the h1 element has some issues below 404px and it would be far too crowded to have everything there. Eventually a dropdown style menu for them could be made fairly easily. The same goes for integrating each theme as a command, though in general most real-life terminals have some sort of gui for appearance options anyway :)

Fixes #16

### CODE REVIEW

**Comment by TechSpiritSS** [comment]
Well, I really liked this concept but add a preview link for this so that I can check it before merging this. You can deploy this on your forked repo pages for a preview.

**Comment by ethapar** [comment]
Here it is: https://ethapar.github.io/Terminal-Portfolio/

**Comment by TechSpiritSS** [comment]
I don't think that's how terminal should look like

image

MS Edge and Google Chrome both showed same result.

**Comment by TechSpiritSS** [comment]
Buttons aren't working

**Comment by ethapar** [comment]
Oh I see what happened. I reorganized index.html to be cleaner and in doing so broke some things. Let me go back and fix it and I'll update when I do.

**Comment by ethapar** [comment]
Okay, I think it should hopefully be working now haha. Basically just forgot that my VSCode has an auto 'beautify' thing that changes indents and such and so that caused git to think there were a whole bunch of conflicts, and when I tried to undo that I accidentally deleted a few lines. Hopefully it should be good to go now! Let me know. Hope you like it :)

**Pull request merged**
