### PR TITLE
responsive

### LINKED ISSUE #108: [Req]: Responsiveness
### Contact Details

techspiritss@duck.com

### Explain the proposed feature

Currently the site is not fully responsive and has some minor bugs. Fix all those non (or less) responsive elements (including themes).

### Explain the possible use cases for the feature

- Improved accessibility:
- Enhanced user experience

### Any other details you would like to provide?

_No response_

### PR DESCRIPTION
**Pull request by khushigarg1**
## Fixes

Fixes #108  by @khushigarg1 

## Types of changes

- [x] Bug/Hot fix (non-breaking change which fixes an bug)
- [x] New feature (non-breaking change which adds a functionality/feature)
- [x] Refactoring Old Code ( non-breaking change replacing already existing code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Preview Link

https://khushigarg1.github.io/Terminal-Portfolio/

## Checklist:

- [x] I have read the **CONTRIBUTING** guidelines in repository.
- [x] My pull request has a descriptive title and is attached to an existing issue.
- [x] I haven't repeated the code and it follows established code style of repository.
- [x] My branch is up-to-date with upstream branch.

### CODE REVIEW

**Comment by TechSpiritSS** [comment]
In desktop variant techspiritss is off set

**Comment by khushigarg1** [comment]
> In desktop variant techspiritss is off set

Now check!

**Comment by TechSpiritSS** [comment]
Typing animation missing

**Comment by khushigarg1** [comment]
> Typing animation missing

done

**Comment by TechSpiritSS** [comment]
need some more edits, check discord for more info

**Comment by khushigarg1** [comment]
> need some more edits, check discord for more info

Okay

**Comment by TechSpiritSS** [comment]
Great 🚀

**Pull request merged**
