### PR TITLE
Add 'help {cmdName}'

### LINKED ISSUE #162: [Req]: add "help {cmdName}" command
### Contact Details

_No response_

### Explain the proposed feature

Add "help {cmdName}" command which gives a full description of the respective command.
Also, add full info about every cmd in the config file.

image
image

### Explain the possible use cases for the feature

_No response_

### Any other details you would like to provide?

_No response_

### PR DESCRIPTION
**Pull request by VaibhavArora314**
## Fixes

Fixes #162 

## Types of changes

- [ ] Bug/Hot fix (non-breaking change which fixes an bug)
- [x] New feature (non-breaking change which adds a functionality/feature)
- [x] Refactoring Old Code ( non-breaking change replacing already existing code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Added "help {cmdName}" command which gives a full description of the respective command.
image
image
Also, added full info about every cmd in the config file. Info is an array of strings which will be used while explaining the cmd.
image

## Preview Link

https://terminal-portfolio-7aqw9pphs-vaibhav31.vercel.app/

## Checklist:

- [x] I have read the **CONTRIBUTING** guidelines in repository.
- [x] My pull request has a descriptive title and is attached to an existing issue.
- [x] I haven't repeated the code and it follows established code style of repository.
- [x] My branch is up-to-date with upstream branch.

### CODE REVIEW

**Comment by TechSpiritSS** [comment]
Add help {cmd} in the description of help so that user will be aware of this.

**Comment by VaibhavArora314** [comment]
Done

**Comment by VaibhavArora314** [comment]
@TechSpiritSS please review the pr. I have made all the required changes.

**Comment by TechSpiritSS** [comment]
Great 🚀

**Pull request merged**
