### PR TITLE
Added Calculator

### LINKED ISSUE #34: Adding the Calculator functionality
Hey @TechSpiritSS .
I've tried adding a calculator functionality to it.
Note :- It can only perform operation on 2 numbers at a time.
It will take 2 numbers as input and then ask which type of operation to be performed.
It can perform operations such as addition, subtraction, subtraction, division, multiplication, modulo, AND, OR on the two given numbers.

I hope it helps.
P.S :- Please go thoroughly through the script.js file because I've made significant changes in it.

Thanks :)

### PR DESCRIPTION
**Pull request by BhagatHarsh**
Used the default Eval function to handle all the calculations

## Fixes

Fixes #34  by @BhagatHarsh

## Types of changes

- [ ] Bug/Hot fix (non-breaking change which fixes an bug)
- [x] New feature (non-breaking change which adds a functionality/feature)
- [ ] Refactoring Old Code ( non-breaking change replacing already existing code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Just addes a simple calculator to the website.
you never know when you need it!

## Preview Link

The changes are really minor but you can preview by cloning my fork [here](https://github.com/BhagatHarsh/Terminal-Portfolio)

Here's how it looks.
image

## Checklist:

- [x] I have read the **CONTRIBUTING** guidelines in repository.
- [x] My pull request has a descriptive title and is attached to an existing issue.
- [x] I haven't repeated the code and it follows established code style of repository.
- [x] My branch is up-to-date with upstream branch.

### CODE REVIEW

**Comment by TechSpiritSS** [comment]
Share me GitHub pages link instead of repository link as it'll be difficult for me to manage clone of everyone's repository

**Comment by BhagatHarsh** [comment]
Please try it out from here [link](https://bhagatharsh.github.io/)

**Comment by BhagatHarsh** [comment]
Im on it!

**Comment by BhagatHarsh** [comment]
@TechSpiritSS Please review the changes.
The preview is [here](https://bhagatharsh.github.io./Terminal-Portfolio/).

**Comment by TechSpiritSS** [comment]
Great 🚀

**Pull request merged**
