### PR TITLE
added education command

### LINKED ISSUE #166: [Req]: Education command
### Contact Details

_No response_

### Explain the proposed feature

It will show, where you got educated.

### Explain the possible use cases for the feature

_No response_

### Any other details you would like to provide?

_No response_

### PR DESCRIPTION
**Pull request by khushigarg1**
## Fixes

Fixes #166  by @khushigarg1 

## Types of changes

- [ ] Bug/Hot fix (non-breaking change which fixes an bug)
- [x] New feature (non-breaking change which adds a functionality/feature)
- [ ] Refactoring Old Code ( non-breaking change replacing already existing code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Preview Link

https://khushigarg1.github.io/Terminal-Portfolio/

## Checklist:

- [x] I have read the **CONTRIBUTING** guidelines in repository.
- [x] My pull request has a descriptive title and is attached to an existing issue.
- [x] I haven't repeated the code and it follows established code style of repository.
- [x] My branch is up-to-date with upstream branch.

### CODE REVIEW

**Comment by TechSpiritSS** [comment]
image

**Comment by khushigarg1** [comment]
> image

Screenshot (90)

**Comment by TechSpiritSS** [comment]
image

**Comment by TechSpiritSS** [comment]
Merge Conflict and same <a> problem

**Comment by TechSpiritSS** [comment]
Education command not working

**Comment by Shubhodaya** [comment]
Hey can I work on it? @TechSpiritSS

**Comment by TechSpiritSS** [comment]
> Hey can I work on it? @TechSpiritSS
let her complete as she's facing minor bugs

**Comment by khushigarg1** [comment]
> Education command not working

now check this please
https://khushigarg1.github.io/Terminal-Portfolio/

**Comment by TechSpiritSS** [comment]
PR is not previous version.

**Pull request closed without merging**
