### PR TITLE
add two new themes vibrant and galaxy

### PR DESCRIPTION
**Pull request by dheerajchhatanidc**
**Fixes**  #125 by @TechSpiritSS 
### Two new themes are added into the Terminal Portfolio (Vibrant and Galaxy)
[Preview Link](https://dheerajchhatanidc.github.io/Terminal-Portfolio/)
image

### **1. Vibrant theme**

image

image

image

### **2. Galaxy Theme**

image

image

image

### CODE REVIEW

**Comment by TechSpiritSS** [comment]
Add the Preview Link as well

**Comment by dheerajchhatanidc** [comment]
> Add the Preview Link as well

[Preview Link](https://dheerajchhatanidc.github.io/Terminal-Portfolio/)

**Comment by TechSpiritSS** [comment]
merge conflicts

**Comment by dheerajchhatanidc** [comment]
@TechSpiritSS resolved the merge conflicts

**Comment by TechSpiritSS** [comment]
Responsiveness Issue

**Pull request closed without merging**
