### PR TITLE
Added typing animation and typing cmd

### LINKED ISSUE #154: [Req]: Text writing animation
### Contact Details

Discord id: vaibhav_#7300

### Explain the proposed feature

Add a text-writing animation and a command to turn it off and on.
Ex:

https://user-images.githubusercontent.com/84830429/212622890-731d30b4-d355-4815-98d8-2376f9dc8db2.mp4

Please assign it to me.

### Explain the possible use cases for the feature

_No response_

### Any other details you would like to provide?

_No response_

### PR DESCRIPTION
**Pull request by VaibhavArora314**
## Fixes 

Fixes #154 

## Types of changes

- [ ] Bug/Hot fix (non-breaking change which fixes an bug)
- [x] New feature (non-breaking change which adds a functionality/feature)
- [x] Refactoring Old Code ( non-breaking change replacing already existing code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Added typing animation.
Also added typing cmd, using which we can see the status of whether typing animation is on or off, and by presenting flags like --on or --off we can turn it on or off. Also by providing a number, the user can set a custom typing speed in ms.

https://user-images.githubusercontent.com/84830429/212666098-c636146a-278d-41f7-9c2f-d9eef3369758.mp4

## Preview Link

https://terminal-portfolio-hrqcu48hz-vaibhav31.vercel.app/

## Checklist:

- [x] I have read the **CONTRIBUTING** guidelines in repository.
- [x] My pull request has a descriptive title and is attached to an existing issue.
- [x] I haven't repeated the code and it follows established code style of repository.
- [x] My branch is up-to-date with upstream branch.

### CODE REVIEW

**Comment by TechSpiritSS** [comment]
- Merge Conflict
- make flag single dash `-` instead of double dash `--`
- cls bug
Apart from these Great Work 🥳

**Comment by VaibhavArora314** [comment]
@TechSpiritSS I have made the required changes and resolved the merge conflict, can you please review it now

**Comment by TechSpiritSS** [comment]
Merge Conflicts

**Comment by VaibhavArora314** [comment]
resolved merge conflict

**Comment by TechSpiritSS** [comment]
Great 🚀

**Pull request merged**
