### PR TITLE
main

### LINKED ISSUE #108: [Req]: Responsiveness
### Contact Details

techspiritss@duck.com

### Explain the proposed feature

Currently the site is not fully responsive and has some minor bugs. Fix all those non (or less) responsive elements (including themes).

### Explain the possible use cases for the feature

- Improved accessibility:
- Enhanced user experience

### Any other details you would like to provide?

_No response_

### PR DESCRIPTION
**Pull request by MridulGupta007**
## Fixes

Fixes #108  by @TechSpiritSS 

## Types of changes

- [ ] Bug/Hot fix (non-breaking change which fixes an bug)
- [x] New feature (non-breaking change which adds a functionality/feature)
- [x] Refactoring Old Code ( non-breaking change replacing already existing code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
 Make the Header of the terminal more responsive to varying widths.
 The position of the elements was not correct with respect to varying widths

## Preview Link
 

   - https://mridulgupta007.github.io/Terminal-Portfolio/

## Checklist:

- [x] I have read the **CONTRIBUTING** guidelines in repository.
- [ ] My pull request has a descriptive title and is attached to an existing issue.
- [x] I haven't repeated the code and it follows established code style of repository.
- [x] My branch is up-to-date with upstream branch.

### CODE REVIEW

**Comment by TechSpiritSS** [comment]
Fill the form and add preview link

**Comment by MridulGupta007** [comment]
I have filled the form and added the preview link

**Comment by TechSpiritSS** [comment]
This is working on an old version and missing my new PR

**Comment by MridulGupta007** [comment]
but while raising the pr, i used git pull, lemme just make a new commit

**Comment by TechSpiritSS** [comment]
It's still not working

**Comment by TechSpiritSS** [comment]
Closing due to inactiveness.

**Pull request closed without merging**
