### PR TITLE
remover anchor tag

### LINKED ISSUE #165: [Bug]: <a> at starting in skills or experience
### Contact Details

_No response_

### What should have happened?

<a> Technical skills are instead of this it should be like 
Technical skills are:- 

### What browsers are you seeing the problem on?

_No response_

### Version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by khushigarg1**
## Fixes

Fixes #165  by @khushigarg1 

## Types of changes

- [x] Bug/Hot fix (non-breaking change which fixes an bug)
- [ ] New feature (non-breaking change which adds a functionality/feature)
- [x] Refactoring Old Code ( non-breaking change replacing already existing code)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** guidelines in repository.
- [x] My pull request has a descriptive title and is attached to an existing issue.
- [x] I haven't repeated the code and it follows established code style of repository.
- [x] My branch is up-to-date with upstream branch.

### CODE REVIEW

**Comment by LiQuiD-404** [comment]
@khushigarg1 This is not a valid contribution.

**Review by LiQuiD-404 — CHANGES_REQUESTED** [review]
You have only changed the indentation and added few spaces.

**Comment by khushigarg1** [comment]
> You have only changed the indentation and added few spaces.

Yess but what else can I do! 
any suggestion ?

**Comment by khushigarg1** [comment]
Screenshot (81)
Screenshot (82)

**Comment by khushigarg1** [comment]
Screenshot (83)
Screenshot (84)

**Comment by TechSpiritSS** [comment]
I know this was a silly bug with just one minor tweak, but I'll allow as she pointed it out as well.

**Review by LiQuiD-404 — COMMENTED** [review]
LGTM ✨

**Pull request merged**
