### PR TITLE
Added `.editorconfig`, Refactored code and added new theme

### LINKED ISSUE #133: [Req]: New theme
### Contact Details

siddhesh.agarwal@gmail.com

### Explain the proposed feature

I propose a new themes:

- The [Dracula theme](https://draculatheme.com/):
  Dracula theme implementations

### Explain the possible use cases for the feature

Dracula theme is one of the most popular themes out there

### Any other details you would like to provide?

_No response_

### PR DESCRIPTION
**Pull request by Siddhesh-Agarwal**
## Fixes

Fixes #133 by @Siddhesh-Agarwal

## Types of changes

- [x] Bug/Hot fix (non-breaking change which fixes an bug)
- [ ] New feature (non-breaking change which adds a functionality/feature)
- [x] Refactoring Old Code ( non-breaking change replacing already existing code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

- Added a `.editorconfig` for standard EOF and tab length across the repository
- Reformatted code according to the configuration settings.
- Added a new theme inspired by the [Dracula Theme](https://draculatheme.com/)

## Preview Link

image

## Checklist:

- [x] I have read the **CONTRIBUTING** guidelines in repository.
- [x] My pull request has a descriptive title and is attached to an existing issue.
- [x] I haven't repeated the code and it follows established code style of repository.
- [x] My branch is up-to-date with upstream branch.

### CODE REVIEW

**Comment by Siddhesh-Agarwal** [comment]
I used the [Fira Code](https://fonts.google.com/share?selection.family=Fira%20Code) font for font ligatures and referred to the [Dracula theme official website](https://draculatheme.com/) for the colour schema.

**Comment by Siddhesh-Agarwal** [comment]
Also, for consistent coding style throughout the repository, I have added a [.editorconfig`](https://editorconfig.org/)

**Comment by TechSpiritSS** [comment]
Add preview link instead of SS and there is a merge conflict

**Comment by Siddhesh-Agarwal** [comment]
I'll fix it ASAP

**Comment by Siddhesh-Agarwal** [comment]
Solved. The branch is safe for merge now.

**Comment by TechSpiritSS** [comment]
preview link?

**Comment by Siddhesh-Agarwal** [comment]
[Preview Link](https://siddhesh-agarwal.github.io/Terminal-Portfolio/)

**Comment by TechSpiritSS** [comment]
History Command not working

**Comment by TechSpiritSS** [comment]
Great 🚀

**Pull request merged**
