### PR TITLE
Themes hover effect and click on text enabled

### LINKED ISSUE #171: [Enhancement]: Themes dropdown customization
### Contact Details

_No response_

### What happened?

In the dropdown list, the CSS doesn't display where the cursor is placed.

### What should have happened?

In the dropdown, there can be some sort of highlighting to indicate which theme I have placed my cursor on.

### What browsers are you seeing the problem on?

_No response_

### Version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PiXeL99-eng**
## Fixes

Fixes #171

## Types of changes

- [ ] Bug/Hot fix (non-breaking change which fixes an bug)
- [ x] New feature (non-breaking change which adds a functionality/feature)
- [ x] Refactoring Old Code ( non-breaking change replacing already existing code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Cursor hover on themes has an effect
CSS changes, using box shadow
Clicking on theme text changes the theme too, not just the circle button

## Preview Link

https://pixel99-eng.github.io/pixel-Terminal-Portfolio/

## Checklist:

- [x ] I have read the **CONTRIBUTING** guidelines in repository.
- [ x] My pull request has a descriptive title and is attached to an existing issue.
- [ x] I haven't repeated the code and it follows established code style of repository.
- [ x] My branch is up-to-date with upstream branch.

### CODE REVIEW

**Comment by PiXeL99-eng** [comment]
I don't know what CNAME is. This file magically appeared and got deleted. Probably happened when I was trying to host the website of github pages

**Comment by TechSpiritSS** [comment]
add the latest commit to this rest is great 🚀

**Comment by TechSpiritSS** [comment]
> I don't know what CNAME is. This file magically appeared and got deleted. Probably happened when I was trying to host the website on github pages

CNAME is a record file for DNS of your Github pages URL

**Comment by PiXeL99-eng** [comment]
Ohh i see

**Comment by PiXeL99-eng** [comment]
Merged the latest commit @TechSpiritSS 
https://pixel99-eng.github.io/pixel-Terminal-Portfolio/

**Comment by TechSpiritSS** [comment]
Great 🚀

**Pull request merged**
