### PR TITLE
style - fixed flickering when getting minimized

### LINKED ISSUE #111: [Bug]: Minimize Button changing location of the Title Bar
### Contact Details

techspiritss@duck.com

### What happened?

msedge_PRrknPnyqq
The bar is moving up on click

### What should have happened?

The bar should remain fixed to its previous position.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ArnabChatterjee20k**
## Fixes
Fixed the screen flickering when minimized

Fixes #111  by @TechSpiritSS 

## Description
Removed the align-center from body which was causing the flickering.

### CODE REVIEW

**Comment by ArnabChatterjee20k** [comment]
https://arnabchatterjee20k.github.io/Terminal-Portfolio/

**Comment by TechSpiritSS** [comment]
msedge_i4706bFmjD
It's still there

**Comment by ArnabChatterjee20k** [comment]
Can u plz confirm now?
https://arnabchatterjee20k.github.io/Terminal-Portfolio/

**Comment by TechSpiritSS** [comment]
Great 🚀

**Pull request merged**
