### PR TITLE
added experience section

### LINKED ISSUE #104: Work Experience
### Contact Details

_No response_

### What happened?

There is not any experience section in portfolio.

### What should have happened?

I want to add one command for experience. Please assign this issue to me?

### What browsers are you seeing the problem on?

_No response_

### Version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by khushigarg1**
## Fixes

Fixes #104 by @khushigarg1 

## Types of changes

- [ ] Bug/Hot fix (non-breaking change which fixes an bug)
- [x] New feature (non-breaking change which adds a functionality/feature)
- [ ] Refactoring Old Code ( non-breaking change replacing already existing code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

I added the experience command in a terminal portfolio so whenever the user writes the experience command it will show work experience.

## Preview Link
 (https://khushigarg1.github.io/Terminal-Portfolio/)  

- [x] I have read the **CONTRIBUTING** guidelines in repository.
- [x] My pull request has a descriptive title and is attached to an existing issue.
- [x] I haven't repeated the code and it follows established code style of repository.
- [x] My branch is up-to-date with upstream branch.

### CODE REVIEW

**Comment by TechSpiritSS** [comment]
Add a preview link for this by deploying it on your github pages and sharing the link here.

**Comment by TechSpiritSS** [comment]
Also complete the form by adding issue number

**Comment by khushigarg1** [comment]
Now completed the form

**Comment by TechSpiritSS** [comment]
are you working on latest commit as Tab Autocomplete isn't working.

**Comment by TechSpiritSS** [comment]
check this bug

**Comment by khushigarg1** [comment]
Please check now.

**Comment by TechSpiritSS** [comment]
still not working, also instead of showing experience directly next to it create a new line

> Title
> Paragraph
> Paragraph

**Review by arjun118 — CHANGES_REQUESTED** [review]
Hey there, You added the same text twice.
Please fix this
pic



Great work!!

**Comment by khushigarg1** [comment]
> still not working, also instead of showing experience directly next to it create a new line
> 
> > Title
> > Paragraph
> > Paragraph

Now check i fixed autocomplete tab issue.

**Comment by TechSpiritSS** [comment]
Great 🚀

**Pull request merged**
